api/urls.py
from django.urls import path

# Views
from .views import ProductoList, ProductoDetalle

urlpatterns = [
    # API
    path('v1/productos/', ProductoList.as_view(), name='producto_list'),
    path('v1/productos/<str:codigo>', ProductoDetalle.as_view(), name='producto_detalle'),

]

app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('bases.urls', 'bases'), namespace='bases')),
    path('inv/', include(('inv.urls', 'inv'), namespace='inv')),
    path('cmp/', include(('cmp.urls', 'cmp'), namespace='cmp')),
    path('fac/', include(('fac.urls', 'fac'), namespace='fac')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
    
    path('admin/', admin.site.urls),
]

inv/urls.py
from django.urls import path
from .views import CategoriaView, CategoriaNew, CategoriaEdit, CategoriaDel, \
    SubCategoriaView, SubCategoriaNew, SubCategoriaEdit, SubCategoriaDel, \
        MarcaView, MarcaNew, MarcaEdit, marca_inactivar, \
            UMView, UMNew, UMEdit, UM_inactivar, \
                ProductoView, ProductoNew, ProductoEdit, Producto_inactivar

urlpatterns = [
    # Categorias
    path('categorias/', CategoriaView.as_view(), name='categoria_list'),
    path('categorias/new', CategoriaNew.as_view(), name='categoria_new'),
    path('categorias/edit/<int:pk>', CategoriaEdit.as_view(), name='categoria_edit'),
    path('categorias/delete/<int:pk>', CategoriaDel.as_view(), name='categoria_del'),
    
    # Sub categorías
    path('subcategorias/', SubCategoriaView.as_view(), name='subcategoria_list'),
    path('subcategorias/new', SubCategoriaNew.as_view(), name='subcategoria_new'),
    path('subcategorias/edit/<int:pk>', SubCategoriaEdit.as_view(), name='subcategoria_edit'),
    path('subcategorias/delete/<int:pk>', SubCategoriaDel.as_view(), name='subcategoria_del'),
    
    # Marca
    path('marcas/', MarcaView.as_view(), name='marca_list'),
    path('marcas/new', MarcaNew.as_view(), name='marca_new'),
    path('marcas/edit/<int:pk>', MarcaEdit.as_view(), name='marca_edit'),
    path('marcas/inactivar/<int:id>', marca_inactivar, name='marca_del'),

    # Unidades de Medida
    path('um/', UMView.as_view(), name='um_list'),
    path('um/new', UMNew.as_view(), name='um_new'),
    path('um/edit/<int:pk>', UMEdit.as_view(), name='um_edit'),
    path('um/inactivar/<int:id>', UM_inactivar, name='um_del'),

    # Productos
    path('productos/', ProductoView.as_view(), name='producto_list'),
    path('productos/new', ProductoNew.as_view(), name='producto_new'),
    path('productos/edit/<int:pk>', ProductoEdit.as_view(), name='producto_edit'),
    path('productos/inactivar/<int:id>', Producto_inactivar, name='inactivar_producto'),

]

bases/models.py
# Django
from django.db import models
from django.contrib.auth.models import User

# App
from django_userforeignkey.models.fields import UserForeignKey

class ClaseModelo(models.Model):
    estado = models.BooleanField(default=True)

    # FC = Fecha Creación - FM = Fecha Modificación
    fc = models.DateTimeField(auto_now_add=True)
    fm = models.DateTimeField(auto_now=True)

    # UC = Usuario Creación - UM = Usuario Modificación
    uc = models.ForeignKey(User, on_delete=models.CASCADE)
    um = models.IntegerField(blank=True, null=True)

    class Meta:
        abstract=True


class ClaseModelo2(models.Model):
    estado = models.BooleanField(default=True)

    # FC = Fecha Creación - FM = Fecha Modificación
    fc = models.DateTimeField(auto_now_add=True)
    fm = models.DateTimeField(auto_now=True)

    # UC = Usuario Creación - UM = Usuario Modificación
    # uc = models.ForeignKey(User, on_delete=models.CASCADE)
    # um = models.IntegerField(blank=True, null=True)
    uc = UserForeignKey(auto_user_add=True, related_name='+')
    um = UserForeignKey(auto_user=True, related_name='+')

    class Meta:
        abstract=True

inv/models.py
from django.db import models

# Clases Modelo
from bases.models import ClaseModelo

class Categoria(ClaseModelo):
    descripcion = models.CharField(
        max_length=100,
        help_text='Descripcion de la categoría',
        unique=True
    )

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Categoria, self).save()

    class Meta:
        verbose_name_plural='Categorias'

class SubCategoria(ClaseModelo):
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    descripcion = models.CharField(
        max_length=100,
        help_text='Descripcion de la categoría',
    )

    def __str__(self):
        return '{}:{}'.format(self.categoria.descripcion, self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(SubCategoria, self).save()

    class Meta:
        verbose_name_plural='Sub Categorías'
        unique_together = ('categoria', 'descripcion')

class Marca(ClaseModelo):
    descripcion = models.CharField(
        max_length=100,
        help_text='Descripción de la Marca',
        unique=True
    )

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Marca, self).save()

    class Meta:
        verbose_name_plural = "Marcas"

class Unidad_medida(ClaseModelo):
    descripcion = models.CharField(
        max_length=100,
        help_text='Descripción de Unidad de Medida',
        unique=True
    )

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Unidad_medida, self).save()

    class Meta:
        verbose_name_plural = "Unidades de medidas"

class Producto(ClaseModelo):
    codigo = models.CharField(
        max_length=20,
        unique=True
    )
    codigo_barra = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=200)
    precio = models.FloatField(default=0)
    existencia = models.IntegerField(default=0)
    ultima_compra = models.DateField(null=True, blank=True)

    marca = models.ForeignKey(Marca, on_delete=models.CASCADE)
    unidad_medida = models.ForeignKey(Unidad_medida, on_delete=models.CASCADE)
    subcategoria = models.ForeignKey(SubCategoria, on_delete=models.CASCADE)

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Producto, self).save()

    class Meta:
        verbose_name_plural = "Productos"
        unique_together = ['codigo', 'codigo_barra']

inv/forms.py
from django import forms

# Models
from .models import Categoria, SubCategoria, Marca, Unidad_medida, Producto

class CategoriaForm(forms.ModelForm):
    class Meta:
        model=Categoria
        fields= ['descripcion', 'estado']
        labels = {'descripcion':'Descripción de la Categoría',
                'estado':'Estado'}
        widget = {'descripcion': forms.TextInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })

class SubCategoriaForm(forms.ModelForm):
    categoria = forms.ModelChoiceField(
        queryset=Categoria.objects.filter(estado=True)
        .order_by('descripcion')
    )
    class Meta:
        model=SubCategoria
        fields= ['categoria', 'descripcion', 'estado']
        labels = {'descripcion':'Sub Categoría',
                'estado':'Estado'}
        widget = {'descripcion': forms.TextInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })
        self.fields['categoria'].empty_label = "Seleccione Categoría"

class MarcaForm(forms.ModelForm):
    class Meta:
        model=Marca
        fields= ['descripcion', 'estado']
        labels = {'descripcion':'Descripción de la Marca',
                'estado':'Estado'}
        widget = {'descripcion': forms.TextInput()}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })

class UMForm(forms.ModelForm):
    class Meta:
        model=Unidad_medida
        fields= ['descripcion', 'estado']
        labels = {'descripcion':'Descripción de Unidad de medida',
                'estado':'Estado'}
        widget = {'descripcion': forms.TextInput()}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })

class ProductoForm(forms.ModelForm):
    class Meta:
        model=Producto
        fields= ['codigo', 'codigo_barra', 'descripcion', 'estado', \
                'precio', 'existencia', 'ultima_compra', 'marca', \
                'subcategoria', 'unidad_medida']

        exclude = ['um', 'fm', 'uc', 'fc']
        widget = {'descripcion': forms.TextInput()}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control w-100'
            })

        self.fields['ultima_compra'].widget.attrs['readonly'] = True
        self.fields['existencia'].widget.attrs['readonly'] = True

inv/views.py
# Django
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib import messages

# Mixins
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin

# Decoradores
from django.contrib.auth.decorators import login_required, permission_required

# Vistas Django
from django.views import generic

# Modelos
from .models import Categoria, SubCategoria, Marca, Unidad_medida, Producto

# Vistas Heredadas
from bases.views import SinPrivilegios

# Forms
from .forms import CategoriaForm, SubCategoriaForm, MarcaForm, UMForm, \
    ProductoForm


# CATEGORÍA

class CategoriaView(SinPrivilegios,\
    generic.ListView):
    permission_required = 'inv.view_categoria'

    model = Categoria
    template_name = 'inv/categoria_list.html'
    context_object_name = 'obj'


class CategoriaNew(SinPrivilegios, SuccessMessageMixin,\
    generic.CreateView):
    permission_required='inv.add_categoria'

    model = Categoria
    template_name='inv/categoria_form.html'
    context_object_name = 'obj'
    form_class=CategoriaForm
    success_url=reverse_lazy('inv:categoria_list')

    success_message="Categoría creada satisfactoriamente"

    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)


class CategoriaEdit(SuccessMessageMixin, SinPrivilegios,\
    generic.UpdateView):
    permission_required='inv.change_categoria'

    model = Categoria
    template_name='inv/categoria_form.html'
    context_object_name = 'obj'
    form_class=CategoriaForm
    success_url=reverse_lazy('inv:categoria_list')

    success_message="Categoría actualizada satisfactoriamente"

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)


class CategoriaDel(SinPrivilegios, generic.DeleteView):
    permission_required='inv.delete_categoria'

    model=Categoria
    template_name='inv/catalogos_del.html'
    context_object_name='obj'
    success_url=reverse_lazy('inv:categoria_list')
    



# SUB CATEGORÍA

class SubCategoriaView(SinPrivilegios,\
    generic.ListView):
    permission_required = 'inv.view_subcategoria'

    model = SubCategoria
    template_name = 'inv/subcategoria_list.html'
    context_object_name = 'obj'
    

class SubCategoriaNew(SinPrivilegios, generic.CreateView):
    permission_required='inv.add_subcategoria'

    model = SubCategoria
    template_name='inv/subcategoria_form.html'
    context_object_name = 'obj'
    form_class=SubCategoriaForm
    success_url=reverse_lazy('inv:subcategoria_list')

    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)


class SubCategoriaEdit(SinPrivilegios, generic.UpdateView):
    permission_required='inv.change_subcategoria'

    model = SubCategoria
    template_name='inv/subcategoria_form.html'
    context_object_name = 'obj'
    form_class=SubCategoriaForm
    success_url=reverse_lazy('inv:subcategoria_list')

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)


class SubCategoriaDel(SinPrivilegios, generic.DeleteView):
    permission_required='inv.delete_subcategoria'

    model=SubCategoria
    template_name='inv/catalogos_del.html'
    context_object_name='obj'
    success_url=reverse_lazy('inv:subcategoria_list')




# MARCA

class MarcaView(SinPrivilegios,\
    generic.ListView):
    permission_required= 'inv.view_marca'

    model = Marca
    template_name = 'inv/marca_list.html'
    context_object_name = 'obj'


class MarcaNew(LoginRequiredMixin, generic.CreateView):
    permission_required= 'inv.add_marca'

    model = Marca
    template_name='inv/marca_form.html'
    context_object_name = 'obj'
    form_class=MarcaForm
    success_url=reverse_lazy('inv:marca_list')

    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)


class MarcaEdit(LoginRequiredMixin, generic.UpdateView):
    permission_required= 'inv.change_marca'

    model = Marca
    template_name='inv/marca_form.html'
    context_object_name = 'obj'
    form_class=MarcaForm
    success_url=reverse_lazy('inv:marca_list')

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)


@login_required(login_url='/login/')
@permission_required('inv.change_marca', login_url='bases:sin_privilegios')
def marca_inactivar(request, id):
    marca = Marca.objects.filter(pk=id).first()
    contexto = {}
    template_name="inv/catalogos_del.html"

    if not marca:
        return redirect('inv:marca_list')

    if request.method == 'GET':
        contexto={'obj':marca}

    if request.method == 'POST':
        marca.estado = False
        marca.save()
        messages.error(
            request,
            '{} Inactivada'.format(
                str(marca),
                )
            )
        return redirect('inv:marca_list')

    return render(request, template_name, contexto)




# UM

class UMView(SinPrivilegios, generic.ListView):
    permission_required='inv.view_um'

    model = Unidad_medida
    template_name = 'inv/um_list.html'
    context_object_name = 'obj'


class UMNew(SinPrivilegios, generic.CreateView):
    permission_required='inv.add_um'
    
    model = Unidad_medida
    template_name='inv/UM_form.html'
    context_object_name = 'obj'
    form_class=UMForm
    success_url=reverse_lazy('inv:um_list')


    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)


class UMEdit(SinPrivilegios, generic.UpdateView):
    permission_required='inv.change_um'

    model = Unidad_medida
    template_name='inv/um_form.html'
    context_object_name = 'obj'
    form_class=UMForm
    success_url=reverse_lazy('inv:um_list')

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)


@login_required(login_url='/login/')
@permission_required('inv.change_um', login_url='bases:sin_privilegios')
def UM_inactivar(request, id):
    um = Unidad_medida.objects.filter(pk=id).first()
    contexto = {}
    template_name="inv/catalogos_del.html"

    if not um:
        return redirect('inv:um_list')

    if request.method == 'GET':
        contexto={'obj':um}

    if request.method == 'POST':
        um.estado = False
        um.save()
        return redirect('inv:um_list')

    return render(request, template_name, contexto)



# Producto

class ProductoView(LoginRequiredMixin, generic.ListView):
    model = Producto
    template_name = 'inv/producto_list.html'
    context_object_name = 'obj'
    login_url = 'bases:login'

class ProductoNew(LoginRequiredMixin, generic.CreateView):
    model = Producto
    template_name='inv/producto_form.html'
    context_object_name = 'obj'
    form_class=ProductoForm
    success_url=reverse_lazy('inv:producto_list')
    login_url='bases:login'

    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)

class ProductoEdit(LoginRequiredMixin, generic.UpdateView):
    model = Producto
    template_name='inv/producto_form.html'
    context_object_name = 'obj'
    form_class=ProductoForm
    success_url=reverse_lazy('inv:producto_list')
    login_url='bases:login'

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)

def Producto_inactivar(request, id):
    producto = Producto.objects.filter(pk=id).first()
    contexto = {}
    template_name="inv/catalogos_del.html"

    if not producto:
        return redirect('inv:producto_list')

    if request.method == 'GET':
        contexto={'obj':producto}

    if request.method == 'POST':
        producto.estado = False
        producto.save()
        return redirect('inv:producto_list')

    return render(request, template_name, contexto)

inv/templates/inv/catalogos_del.html
{% extends 'base/base.html' %}
 
{% block page_content %}
<form method="POST" class="form-inline">
    {% csrf_token %}
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-danger shadow h-100 py-2">
            <div class="card-body">
            <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                    <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">Eliminar {{ obj.descripcion }}?</div>
                    <button type="submit" class="btn btn-danger"><i class="far fa-question-circle"></i> Si, Eliminar</button>
                    <!-- <a href="{% url 'inv:categoria_list' %}" class="btn btn-success"><span class="fa fa-undo"> Cancelar</span></a> -->
                    <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-success"><span class="fa fa-undo"> Cancelar</span></a>


                </div>
                <div class="col-auto">
                    <i class="far fa-question-circle fa-2x text-gray-300"></i>
                </div>
            </div>
            </div>
        </div>
    </div>
</form>
 
 
{% endblock %}
{% block js_page %}
{% endblock %}

inv/templates/inv/categoria_list.html
{% extends 'base/base.html' %}

{% block page_content %}
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Listado de Categorias</h6>
      <div class="dropdown no-arrow">
        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
          <div class="dropdown-header">Acciones</div>
          <a class="dropdown-item" href="{% url 'inv:categoria_new' %}"><i class="far fa-calendar-plus"></i> Nueva</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
        {% if not obj %}
            <div class="alert alert-info">No hay categorías</div>
        {% else %}
        
        <table class="table table-striped table-hover">
            <thead>
                <th>Id</th>
                <th>Descripción</th>
                <th>Estado</th>
                <th>F. Creado</th>
                <th>Fecha Modif.</th>
                <th class="all">Acciones</th>
            </thead>
            <tbody>
                {% for item in obj %}
                    <tr>
                        <td>{{ item.id }}</td>
                        <td>{{ item.descripcion }}</td>
                        <td>{{ item.estado|yesno:"Activo, Inactivo" }}</td>
                        <td>{{ item.fc|date:"d/m/Y H:i:s" }}</td>
                        <td>{{ item.fm|date:"d/m/Y H:i:s" }}</td>
                        <td>
                            <a href="{% url 'inv:categoria_edit' item.id %}" class="btn btn-warning btn-circle"><i class="far fa-edit"></i></a>
                            <a href="{% url 'inv:categoria_del' item.id %}" class="btn btn-danger btn-circle"><i class="far fa-trash-alt"></i></a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
  </div>
{% endblock %}

{% block js_page %}
<script>
  // Llama dataTables
  $(document).ready(function() {
    $('.table').DataTable();
  });
</script>
{% endblock %}

inv/templates/inv/marca_list.html
{% extends 'base/base.html' %}

{% block page_content %}
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Listado de Marcas</h6>
      <div class="dropdown no-arrow">
        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
          <div class="dropdown-header">Acciones</div>
          <a class="dropdown-item" href="{% url 'inv:marca_new' %}"><i class="far fa-calendar-plus"></i> Nueva</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
        {% if not obj %}
            <div class="alert alert-info">No hay marcas</div>
        {% else %}
        
        <table class="table table-striped table-hover">
            <thead>
                <th>Id</th>
                <th>Descripción</th>
                <th>Estado</th>
                <th>F. Creado</th>
                <th>Fecha Modif.</th>
                <th class="all">Acciones</th>
            </thead>
            <tbody>
                {% for item in obj %}
                    <tr>
                        <td>{{ item.id }}</td>
                        <td>{{ item.descripcion }}</td>
                        <td>{{ item.estado|yesno:"Activo, Inactivo" }}</td>
                        <td>{{ item.fc|date:"d/m/Y H:i:s" }}</td>
                        <td>{{ item.fm|date:"d/m/Y H:i:s" }}</td>
                        <td>
                            <a href="{% url 'inv:marca_edit' item.id %}" class="btn btn-warning btn-circle"><i class="far fa-edit"></i></a>
                            <a href="{% url 'inv:marca_del' item.id %}" class="btn btn-danger btn-circle"><i class="far fa-thumbs-down"></i></a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
  </div>
{% endblock %}

{% block js_page %}
<script>
  // Llama dataTables
  $(document).ready(function() {
    $('.table').DataTable();
  });
</script>
{% endblock %}

inv/templates/inv/subcategoria_list.html
{% extends 'base/base.html' %}

{% block page_content %}
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Listado de Sub Categorías</h6>
      <div class="dropdown no-arrow">
        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
          <div class="dropdown-header">Acciones</div>
          <a class="dropdown-item" href="{% url 'inv:subcategoria_new' %}"><i class="far fa-calendar-plus"></i> Nueva</a>
        </div>
      </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
        {% if not obj %}
            <div class="alert alert-info">No hay sub categorías</div>
        {% else %}
        
        <table class="table table-striped table-hover">
            <thead>
                <th>Categoría</th>
                <th>Id</th>
                <th>Descripción</th>
                <th>Estado</th>
                <th>F. Creado</th>
                <th>Fecha Modif.</th>
                <th class="all">Acciones</th>
            </thead>
            <tbody>
                {% for item in obj %}
                    <tr>
                        <th>{{ item.categoria }}</th>
                        <td>{{ item.id }}</td>
                        <td>{{ item.descripcion }}</td>
                        <td>{{ item.estado|yesno:"Activo, Inactivo" }}</td>
                        <td>{{ item.fc|date:"d/m/Y H:i:s" }}</td>
                        <td>{{ item.fm|date:"d/m/Y H:i:s" }}</td>
                        <td>
                            <a href="{% url 'inv:subcategoria_edit' item.id %}" class="btn btn-warning btn-circle"><i class="far fa-edit"></i></a>
                            <a href="{% url 'inv:subcategoria_del' item.id %}" class="btn btn-danger btn-circle"><i class="far fa-trash-alt"></i></a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
  </div>
{% endblock %}

{% block js_page %}
<script>
  // Llama dataTables
  $(document).ready(function() {
    $('.table').DataTable();
  });
</script>
{% endblock %}

inv/templates/inv/um_list.html
{% extends 'base/base.html' %}

{% block page_content %}
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Listado de Sub Categorías</h6>
      <div class="dropdown no-arrow">
        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
          <div class="dropdown-header">Acciones</div>
          <a class="dropdown-item" href="{% url 'inv:um_new' %}"><i class="far fa-calendar-plus"></i> Nueva</a>
        </div>
      </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
        {% if not obj %}
            <div class="alert alert-info">No hay Unidades de Medidas</div>
        {% else %}
        
        <table class="table table-striped table-hover">
            <thead>
                <th>Id</th>
                <th>Descripción</th>
                <th>Estado</th>
                <th>F. Creado</th>
                <th>Fecha Modif.</th>
                <th class="all">Acciones</th>
            </thead>
            <tbody>
                {% for item in obj %}
                    <tr>
                        <td>{{ item.id }}</td>
                        <td>{{ item.descripcion }}</td>
                        <td>{{ item.estado|yesno:"Activo, Inactivo" }}</td>
                        <td>{{ item.fc|date:"d/m/Y H:i:s" }}</td>
                        <td>{{ item.fm|date:"d/m/Y H:i:s" }}</td>
                        <td>
                          <a href="{% url 'inv:um_edit' item.id %}" class="btn btn-warning btn-circle"><i class="far fa-edit"></i></a>
                          <a href="{% url 'inv:um_del' item.id %}" class="btn btn-danger btn-circle"><i class="far fa-thumbs-down"></i></a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
  </div>
{% endblock %}

{% block js_page %}
<script>
  // Llama dataTables
  $(document).ready(function() {
    $('.table').DataTable();
  });
</script>
{% endblock %}