api/urls.py
from django.urls import path

# Views
from .views import ProductoList, ProductoDetalle

urlpatterns = [
    # API
    path('v1/productos/', ProductoList.as_view(), name='producto_list'),
    path('v1/productos/<str:codigo>', ProductoDetalle.as_view(), name='producto_detalle'),

]

app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('bases.urls', 'bases'), namespace='bases')),
    path('inv/', include(('inv.urls', 'inv'), namespace='inv')),
    path('cmp/', include(('cmp.urls', 'cmp'), namespace='cmp')),
    path('fac/', include(('fac.urls', 'fac'), namespace='fac')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
    
    path('admin/', admin.site.urls),
]

cmp/urls.py
from django.urls import path
from .views import ProveedorView, ProveedorNew, ProveedorEdit, proveedorInactivar, \
    ComprasView, compras, CompraDetDelete

from .reportes import reporte_compras, imprimir_compra

urlpatterns = [
    # Proveedores
    path('proveedores/', ProveedorView.as_view(), name='proveedor_list'),
    path('proveedores/new', ProveedorNew.as_view(), name='proveedor_new'),
    path('proveedores/edit/<int:pk>', ProveedorEdit.as_view(), name='proveedor_edit'),
    path('proveedores/inactivar/<int:id>', proveedorInactivar, name='proveedor_inactivar'),

    # Compras
    path('compras/', ComprasView.as_view(), name='compras_list'),
    path('compras/new', compras, name='compras_new'),
    path('compras/edit/<int:compra_id>', compras, name='compras_edit'),
    path('compras/<int:compra_id>/delete/<int:pk>', CompraDetDelete.as_view(), name='compras_del'),

    path('compras/listado', reporte_compras, name='compras_print_all'),
    path('compras/<int:compra_id>/imprimir', imprimir_compra, name='compras_print_one'),

]

cmp/models.py
# Django
from django.db import models

# Modelos
from bases.models import ClaseModelo
from inv.models import Producto

# Para usar Signals
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver

# Utilidades
from django.db.models import Sum

class Proveedor(ClaseModelo):
    descripcion=models.CharField(
        max_length=100,
        unique=True
    )
    direccion=models.CharField(
        max_length=250,
        null=True, blank=True
    )
    contacto=models.CharField(
        max_length=100
    )
    telefono=models.CharField(
        max_length=10,
        null=True, blank=True
    )
    email=models.CharField(
        max_length=250,
        null=True, blank=True
    )

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion=self.descripcion.upper()
        super(Proveedor, self).save()

    class Meta:
        verbose_name_plural = 'Proveedores'

# Encabezado de compras
class ComprasEnc(ClaseModelo):
    fecha_compra=models.DateField(null=True, blank=True)
    observacion=models.TextField(blank=True, null=True)
    no_factura=models.CharField(max_length=100)
    fecha_factura=models.DateField()
    sub_total=models.FloatField(default=0)
    descuento=models.FloatField(default=0)
    total=models.FloatField(default=0)

    proveedor=models.ForeignKey(Proveedor, on_delete=models.CASCADE)
    
    def __str__(self):
        return '{}'.format(self.observacion)

    def save(self):
        self.observacion = self.observacion.upper()
        self.total = self.sub_total - self.descuento
        super(ComprasEnc, self).save()

    class Meta:
        verbose_name_plural = 'Encabezados de Compras'
        verbose_name = 'Encabezado de Compra'


# Detalle de Compras
class ComprasDet(ClaseModelo):
    compra=models.ForeignKey(ComprasEnc, on_delete=models.CASCADE)
    producto=models.ForeignKey(Producto, on_delete=models.CASCADE)

    cantidad=models.BigIntegerField(default=0)
    precio_prv=models.FloatField(default=0)
    sub_total=models.FloatField(default=0)
    descuento=models.FloatField(default=0)
    total=models.FloatField(default=0)
    costo=models.FloatField(default=0)

    def __str__(self):
        return '{}'.format(self.producto)
    
    def save(self):
        self.sub_total = float(float(int(self.cantidad)) * float(self.precio_prv))
        self.total = self.sub_total - float(self.descuento)
        super(ComprasDet, self).save()
    
    class Meta:
        verbose_name_plural = 'Detalle de Compras'
        verbose_name = 'Detalle de Compra'

# Decimos con el siguiente decorador, que la siguiente función se va a disparar cuándo se cumpla la siguiente declaración. (Enviada como parámetros)
#En este caso, se disparará cuándo se borre un registro de 'ComprasDet'
@receiver(post_delete, sender=ComprasDet)
def detalle_compra_borrar(sender, instance, **kwargs):
    id_producto = instance.producto.id
    id_compra = instance.compra.id

    enc = ComprasEnc.objects.filter(pk=id_compra).first()
    if enc:
        sub_total = ComprasDet.objects.filter(compra=id_compra).aggregate(Sum('sub_total'))
        descuento = ComprasDet.objects.filter(compra=id_compra).aggregate(Sum('descuento'))
        enc.sub_total=sub_total['sub_total__sum']
        enc.descuento=descuento['descuento__sum']
        enc.save()

    prod=Producto.objects.filter(pk=id_producto).first()

    if prod:
        cantidad = int(prod.existencia) - int(instance.cantidad)
        prod.existencia = cantidad
        prod.save()

@receiver(post_save, sender=ComprasDet)
def detalle_compra_guardar(sender, instance, **kwargs):
    id_producto = instance.producto.id
    fecha_compra = instance.compra.fecha_compra

    prod=Producto.objects.filter(pk=id_producto).first()

    if prod:
        cantidad = int(prod.existencia) + int(instance.cantidad)
        prod.existencia = cantidad
        prod.ultima_compra = fecha_compra
        prod.save()

cmp/forms.py
from django import forms

# Modelos
from .models import Proveedor, ComprasEnc

class ProveedorForm(forms.ModelForm):
    email = forms.EmailField(max_length=254)

    class Meta:
        model=Proveedor
        exclude = ['um', 'fm', 'uc', 'fc']
        widget={'descripcion': forms.TextInput()}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control w-100'
            })

class ComprasEncForm(forms.ModelForm):
    fecha_compra = forms.DateInput()
    fecha_factura = forms.DateInput()

    class Meta:
        model=ComprasEnc
        fields=['proveedor', 'fecha_compra', 'observacion', 'no_factura', 'fecha_factura', 'sub_total', 'descuento', 'total']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })
        self.fields['fecha_compra'].widget.attrs['readonly'] = True
        self.fields['fecha_factura'].widget.attrs['readonly'] = True
        self.fields['sub_total'].widget.attrs['readonly'] = True
        self.fields['descuento'].widget.attrs['readonly'] = True
        self.fields['total'].widget.attrs['readonly'] = True

cmp/views.py
# Django
from django.shortcuts import render, redirect
from django.views import generic
from django.urls import reverse_lazy

from django.http import HttpResponse


# Mixins
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin

# Decoradores
from django.contrib.auth.decorators import login_required, permission_required

# Models
from .models import Proveedor, ComprasEnc, ComprasDet

# Modelos Externos
from inv.models import Producto

# Herencias
from bases.views import SinPrivilegios

# Forms
from .forms import ProveedorForm, ComprasEncForm

# Utilidades
import json
import datetime
from django.db.models import Sum




# Proveedor

class ProveedorView(SinPrivilegios, generic.ListView):
    permission_required='cmp.view_proveedor'

    model = Proveedor
    template_name = 'cmp/proveedor_list.html'
    context_object_name = 'obj'


class ProveedorNew(SinPrivilegios, SuccessMessageMixin,\
    generic.CreateView):
    permission_required='cmp.add_proveedor'

    model = Proveedor
    template_name='cmp/proveedor_form.html'
    context_object_name = 'obj'
    form_class=ProveedorForm
    success_url=reverse_lazy('cmp:proveedor_list')
    success_message='Proveedor Creado'

    def form_valid(self, form):
        form.instance.uc = self.request.user
        print(self.request.user.id)
        return super().form_valid(form)


class ProveedorEdit(SinPrivilegios, SuccessMessageMixin,\
    generic.UpdateView):
    permission_required='cmp.change_proveedor'

    model = Proveedor
    template_name='cmp/proveedor_form.html'
    context_object_name = 'obj'
    form_class=ProveedorForm
    success_url=reverse_lazy('cmp:proveedor_list')
    success_message='Proveedor Editado'

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)


@login_required(login_url='/login/')
@permission_required('cmp.change_proveedor', login_url='bases:sin_privilegios')
def proveedorInactivar(request, id):
    template_name='cmp/inactivar_prv.html'
    contexto={}
    prv = Proveedor.objects.filter(pk=id).first()

    if not prv:
        return HttpResponse('Proveedor no existe '+str(id))

    if request.method == 'GET':
        contexto={'obj':prv}

    if request.method == 'POST':
        prv.estado=False
        prv.save()
        contexto={'obj':'OK'}
        return HttpResponse('Proveedor Inactivado')

    return render(request, template_name, contexto)



# Compras

class ComprasView(SinPrivilegios, generic.ListView):
    permission_required='cmp.view_comprasenc'

    model = ComprasEnc
    template_name = 'cmp/compras_list.html'
    context_object_name = 'obj'


@login_required(login_url='/login/')
@permission_required('cmp.view_comprasenc', login_url='bases:sin_privilegios')
def compras(request, compra_id=None):
    template_name='cmp/compras.html'
    prod=Producto.objects.filter(estado=True)
    form_compras = {}
    contexto = {}

    if request.method == 'GET':
        form_compras = ComprasEncForm()
        enc = ComprasEnc.objects.filter(pk=compra_id).first()

        if enc:
            det = ComprasDet.objects.filter(compra=enc)

            fecha_compra = datetime.date.isoformat(enc.fecha_compra)
            fecha_factura = datetime.date.isoformat(enc.fecha_factura)
            e = {
                'fecha_compra':fecha_compra,
                'proveedor':enc.proveedor,
                'observacion':enc.observacion,
                'no_factura':enc.no_factura,
                'fecha_factura':fecha_factura,
                'sub_total':enc.sub_total,
                'descuento':enc.descuento,
                'total':enc.total
            }

            # Con lo siguiente, establecemos valores por defecto en el formulario
            form_compras = ComprasEncForm(e)
        else:
            det=None
        
        contexto= {'productos':prod, 'encabezado':enc, 'detalle':det, 'form_enc':form_compras}


    if request.method == 'POST':
        # Obtenemos los datos del formulario
        print(request.POST)
        fecha_compra = request.POST.get('fecha_compra')
        observacion = request.POST.get('observacion')
        no_factura = request.POST.get('no_factura')
        fecha_factura = request.POST.get('fecha_factura')
        proveedor = request.POST.get('proveedor')
        sub_total = 0
        descuento = 0
        total = 0

        if not compra_id:
            prov=Proveedor.objects.get(pk=proveedor)
            # Creando Valores en la Base de datos 'ComprasEnc'
            enc = ComprasEnc(
                fecha_compra=fecha_compra,
                observacion=observacion,
                no_factura=no_factura,
                fecha_factura=fecha_factura,
                proveedor=prov,
                uc = request.user
            )
            # Como sabes, hace falta guardarlo, y lo hacemos a continuación con '.save()'
            # Antes preguntamos si existe, claro :)
            if enc:
                enc.save()
                # Rellenamos el parámetro 'compra_id' con su nuevo id
                compra_id=enc.id
        
        else:
            # Ahora que el id ya existe en la variable 'compra_id', rellenamos la información
            enc=ComprasEnc.objects.filter(pk=compra_id).first()

            if enc:
                enc.fecha_compra=fecha_compra
                enc.observacion=observacion
                enc.no_factura=no_factura
                enc.fecha_factura=fecha_factura
                enc.um = request.user.id

                enc.save()
        
        if not compra_id:
            return redirect('cmp:compras_list')

        producto = request.POST.get('id_id_producto')
        cantidad = request.POST.get('id_cantidad_detalle')
        precio = request.POST.get('id_precio_detalle')
        sub_total_detalle = request.POST.get('id_sub_total_detalle')
        descuento_detalle = request.POST.get('id_descuento_detalle')
        total_detalle = request.POST.get('id_total_detalle')

        prod = Producto.objects.get(pk=producto)

        det = ComprasDet(
            compra=enc,
            producto=prod,
            cantidad=cantidad,
            precio_prv=precio,
            descuento=descuento_detalle,
            costo=0,
            uc = request.user
        )

        if det:
            # Si se logró crear el objeto, lo guardamos
            det.save()

            sub_total=ComprasDet.objects.filter(compra=compra_id).aggregate(Sum('sub_total'))
            descuento=ComprasDet.objects.filter(compra=compra_id).aggregate(Sum('descuento'))
            enc.sub_total = sub_total['sub_total__sum']
            enc.descuento = descuento['descuento__sum']
            enc.save()

        return redirect('cmp:compras_edit', compra_id=compra_id)
    
    return render(request, template_name, contexto)


class CompraDetDelete(SinPrivilegios, generic.DeleteView):
    permission_required = 'cmp.delete_comprasdet'
    model = ComprasDet
    template_name = 'cmp/compras_det_del.html'
    context_object_name = 'obj'

    def get_success_url(self):
            compra_id=self.kwargs['compra_id']
            return reverse_lazy('cmp:compras_edit', kwargs={'compra_id': compra_id})

cmp/templates/cmp/compras_det_del.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        <form role="form" action="{% url 'cmp:compras_del' obj.compra.id obj.pk %}" method="post"  class="form-inline">
            <div class="col-xl-12 col-md-12 mb-12">
                <div class="card border-left-danger shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            Eliminar Detalle
                        </div>
                        <div class="dropdown-divider"></div>
                        {% csrf_token %}
                        <div class="row">
                            ¿Eliminar {{ obj.producto }} de compra número <b>{{ obj.compra.id}} </b> ?
                        </div>
                        <div class="dropdown-divider"></div>
                        <div class="row">
                            <div class="col">
                                <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Si, Eliminar</button>
                                <button type="button" class="btn btn-success" onclick="return cerrar_modal()">
                                        Cancelar
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="far fa-calendar-plus fa-2x text-gray-300"></i>
                    </div>
                    </div>
                </div>
                </div>
            </div>
        </form>
    </div>
</div> 

cmp/templates/cmp/compras_list.html
{% extends 'base/base.html' %}

{% block page_content %}
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Listado de Compras</h6>
      <div class="dropdown no-arrow">
        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
          <div class="dropdown-header">Acciones</div>
            <a class="dropdown-item" href="{% url 'cmp:compras_new' %}"><i class="far fa-calendar-plus"></i>Nueva</a>
            <a class="dropdown-item" href="{% url 'cmp:compras_print_all' %}" target="reportes"><i class="fas fa-print"></i>Listado</a>
        </div>
      </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
        {% if not obj %}
            <div class="alert alert-info">No hay compras aún</div>
        {% else %}
        
        <table class="table table-striped table-hover dt-responsive nowrap" style="width:100% !important;">
            <thead>
                <th>Id</th>
                <th>Fecha</th>
                <th>Nº Factura</th>
                <th>F. Factura</th>
                <th>Observacion</th>
                <th>Sub Total</th>
                <th>Descuento</th>
                <th>Total</th>
                <th>Estado</th>
                <th class="all">Acciones</th>
            </thead>
            <tbody>
                {% for item in obj %}
                    <tr>
                        <td>{{ item.id }}</td>
                        <td>{{ item.fecha_compra }}</td>
                        <td>{{ item.no_factura }}</td>
                        <td>{{ item.fecha_factura }}</td>
                        <td>{{ item.observacion }}</td>
                        <td>{{ item.sub_total }}</td>
                        <td>{{ item.descuento }}</td>
                        <td>{{ item.total }}</td>
                        <td>{{ item.estado|yesno:"Activo, Inactivo" }}</td>
                        <td>
                          <a class="btn btn-warning btn-circle" href="{% url 'cmp:compras_edit' item.id %}"><i class="far fa-edit"></i></a>

                          <a class="btn btn-success btn-circle" href="{% url 'cmp:compras_print_one' item.id %}" target="reportes"><i class="fas fa-print"></i></a>

                          {% comment %} <button onclick="return abrir_modal('URL AQUI')" class="btn btn-warning btn-circle"><i class="far fa-edit"></i></button> {% endcomment %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
  </div>
{% endblock %}

{% block js_page %}
<script>
// Call the dataTables jQuery plugin
$(document).ready(function() {
  $('.table').DataTable({
    "language": {
      "sProcessing": "Procesando...",
      "sLengthMenu": "Mostrar _MENU_ registros",
      "sZeroRecords": "No se encontraron resultados",
      "sEmptyTable": "Ningún dato disponible en esta tabla",
      "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
      "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
      "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
      "sInfoPostFix": "",
      "sSearch": "Buscar:",
      "sUrl": "",
      "sInfoThousands": ",",
      "sLoadingRecords": "Cargando...",
      "oPaginate": {
          "sFirst": "<span class='fa fa-angle-double-left'></span>",
          "sLast": "<span class='fa fa-angle-double-right'></span>",
          "sNext": "<span class='fa fa-angle-right'></span>",
          "sPrevious": "<span class='fa fa-angle-left'></span>"
      },
      "oAria": {
          "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
          "sSortDescending": ": Activar para ordenar la columna de manera descendente"
      }
    }
  });
});
</script>
{% endblock %}

cmp/templates/cmp/compras_print_all.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Listado de Compras</title>

    <style type="text/css">
        @page {
            size: letter;
            margin: 1cm;
        }
        .table {
            width: 100%;
            max-width: 100%;
            margin-bottom: 5px;
            background-color: #fff;
        }
        .table th,
        .table td {
            padding: 5px;
            vertical-align: top;
            border-top: 1px solid #000;
            text-align: center;
        }
        .table thead th {
            vertical-align: bottom;
            border-bottom: 2px solid #000;
        }
        .table tbody + tbody {
            border-top: 2px solid #000;
        }
        .table .table {
            background-color: #fff ;
        }
        .list-group {
            display: block;
            width: 100%;
            list-style: none;
            margin-top: 15px;
            margin-bottom: 15px;
        }
        .list-group p {
            width: 100%;
            height: 20px;
            line-height: 20px;
            list-style: none;
            font-size: 1.1em;
        }

    </style>
</head>
<body>
    <div class="container">
        <div class="card">
            <div class="card-header">
                <h4>Sistemas de Compras DEBS</h4>
                <h3>Reporte de compras al {{ today|date:"d/m/Y" }}</h3>
            </div>

            <table class="table">
                <thead>
                    <tr>
                        <th>No. Compra</th>
                        <th>Proveedor</th>
                        <th>Fecha</th>
                        <th>Total</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in obj %}
                    <tr>
                        <td>{{item.id}}</td>
                        <td>{{item.proveedor}}</td>
                        <td>{{item.fecha_compra | date:"d/m/Y"}}</td>
                        <td>{{item.total}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</body>
</html>

cmp/templates/cmp/inactivar_prv.html
<div class="modal-dialog modal-sm">
    <div class="modal-content">
        <form method="POST" class="form-inline">
            {% csrf_token %}
            <div class="col-xl-12 col-md-12 mb-4 mt-4">
                <div class="card border-left-danger shadow h-100 py-2">
                    <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                                <div class="alert">¿Inactivar {{ obj.descripcion }}?</div>
                            </div>
                            <button class="btn btn-danger mb-2" id="btnInactivar"><i class="far fa-question-circle"></i> Si, Eliminar</button>
                            
                            <button type="button" class="btn btn-success" onclick="return cerrar_modal()">
                                    Cancelar
                                </button>

                        </div>
                        <div class="col-auto">
                            <i class="far fa-question-circle fa-2x text-gray-300"></i>
                        </div>
                    </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

<script>
$(document).ready(function () {

    var token = $('input[name=csrfmiddlewaretoken]').val();

    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
                xhr.setRequestHeader("X-CSRFToken", token);
            }
        }
    });

    $('#btnInactivar').click(function (e) {
        e.preventDefault();
        // alert('Works!')
        var id = {{obj.id}};
        var template="{% url 'cmp:proveedor_inactivar' obj.id %}";
        {% comment %} template += id;  {% endcomment %}
        var data = {'id': id}

        data = JSON.stringify(data);

        $.ajax({
            type: 'POST',
            url: template,
            data: data,
            beforeSend: function (xhr, settings) {
                $.ajaxSettings.beforeSend(xhr, settings);
            },
            success: function (response) {
                console.log(response);
                cerrar_modal();
                {% comment %} alert(response); {% endcomment %}
                var tipo= (response.startsWith('Proveedor no existe') ? 'red':'green');
                mensaje(response, tipo);
            },
            error: function (jqXHR, textStatus, errorThow) {
                console.log(textStatus, errorThow);
                var tipo= (response.startsWith('Proveedor no existe') ? 'red':'green');
                mensaje(errorThow, tipo);
                cerrar_modal();                
            },
        });
    });
});
</script>

cmp/templates/cmp/proveedor_form.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        {% if obj %}
        <form method="POST" role="form" class="form-inline" action="{% url 'cmp:proveedor_edit' obj.pk %}">
        {% else %}
        <form method="POST" role="form" class="form-inline" action="{% url 'cmp:proveedor_new' %}">        
        {% endif %}        
            {% csrf_token %}
            <div class="col-xl-12 col-md-12 mb-6">
                {% if obj %}
                <div class="card border-left-warning shadow h-100 py-2">
                {% else %}
                <div class="card border-left-success shadow h-100 py-2">
                {% endif %}
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                    {% if obj %} Editar {% else %} Crear {% endif %} Proveedor
                                </div>
                                <div class="dropdown-divider"></div>
                                    <div class="row">
                                        {{ form.as_p }}                             
                                    </div>     
                                    
                                <div class="dropdown-divider"></div>
                                <div class="row">
                                    <div class="col">
                                        <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>
                                        <button type="button" class="btn btn-success" onclick="return cerrar_modal()">
                                            Cancelar
                                        </button>
                                        <!-- <a href="{% url 'cmp:proveedor_list' %}" class="btn btn-success"><span class="fa fa-undo"> Cancelar</span></a> -->
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

cmp/templates/cmp/proveedor_list.html
{% extends 'base/base.html' %}

{% block page_content %}
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Listado de Proveedores</h6>
      <div class="dropdown no-arrow">
        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
          <div class="dropdown-header">Acciones</div>
          <a class="dropdown-item" id="crear_proveedor" href="#"><i class="far fa-calendar-plus"></i> Crear Proveedor</a>
        </div>
      </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
        {% if not obj %}
            <div class="alert alert-info">No hay proveedores almacenados</div>
        {% else %}
        
        <table class="table table-striped table-hover">
            <thead>
                <th>Id</th>
                <th>Descripción</th>
                <th>Dirección</th>
                <th>Contacto</th>
                <th>Teléfono</th>
                <th>Email</th>
                <th>Estado</th>
                <th class="all">Acciones</th>
            </thead>
            <tbody>
                {% for item in obj %}
                    <tr>
                        <td>{{ item.id }}</td>
                        <td>{{ item.descripcion }}</td>
                        <td>{{ item.direccion }}</td>
                        <td>{{ item.contacto }}</td>
                        <td>{{ item.telefono }}</td>
                        <td>{{ item.email }}</td>
                        <td>{{ item.estado|yesno:"Activo, Inactivo" }}</td>
                        <td>
                          <button onclick="return abrir_modal('{% url 'cmp:proveedor_edit' item.id %}')" class="btn btn-warning btn-circle"><i class="far fa-edit"></i></button>
                          <button onclick="return abrir_modal('{% url 'cmp:proveedor_inactivar' item.id %}')" class="btn btn-danger btn-circle"><i class="far fa-thumbs-down"></i></button>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
  </div>
{% endblock %}

{% block js_page %}
<script>
  // Llama dataTables
  $(document).ready(function() {
    $('.table').DataTable();
  });

</script>
{% endblock %}